# -*- coding: utf-8 -*-
"""genomic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AfiUMzN1OU41kv27uUylHOnq44hcBlFR
"""

import os
import glob
import torch
import torch.nn as nn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from torch.utils.data import Dataset, DataLoader
from transformers import BertConfig, BertModel
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, f1_score, roc_auc_score,
    precision_score, recall_score, confusion_matrix, roc_curve
)

print("All imports OK")
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "Not available — using CPU")

from google.colab import drive
drive.mount('/content/drive')

ZIP_PATH = "/content/drive/MyDrive/genomic_dataset.zip"

import zipfile
print("Unzipping... this takes 1-2 minutes")
with zipfile.ZipFile(ZIP_PATH, 'r') as z:
    z.extractall("/content/")
print("Done unzipping")

# Correct path — extracted directly here
DATASET_ROOT = "/content/genomic data set"
TUMOR_DIR    = os.path.join(DATASET_ROOT, "tumor")
HEALTHY_DIR  = os.path.join(DATASET_ROOT, "healthy")

# Sanity check
tumor_samples   = [d for d in glob.glob(os.path.join(TUMOR_DIR,   "*")) if os.path.isdir(d)]
healthy_samples = [d for d in glob.glob(os.path.join(HEALTHY_DIR, "*")) if os.path.isdir(d)]
print(f"Tumor  sample folders: {len(tumor_samples)}")
print(f"Healthy sample folders: {len(healthy_samples)}")

CONFIG = {
    # Which expression column to use from the TSV
    # Options: "tpm_unstranded", "fpkm_unstranded", "unstranded"
    "expression_col": "tpm_unstranded",

    # Top N most variable genes — 1500 is good for 800 samples on T4
    "top_n_genes": 500,

    # BERT architecture
    "hidden_size": 256,
    "num_attention_heads": 8,
    "num_hidden_layers": 4,
    "intermediate_size": 512,
    "dropout": 0.35,

    # Training — tuned for overnight T4 run
    "batch_size": 16,
    "learning_rate": 1e-4,
    "num_epochs": 50,
    "patience": 15,
    "test_size": 0.15,
    "val_size":  0.15,
    "seed": 42,
}

# ── CELL 5: Data loading (complete, memory-efficient) ─────────

import gc
import random

# ── define load_one_sample first ──────────────────────────────
def load_one_sample(sample_dir, expression_col):
    tsv_files = glob.glob(os.path.join(sample_dir, "*.tsv"))
    if not tsv_files:
        raise FileNotFoundError(f"No TSV found in {sample_dir}")
    df = pd.read_csv(tsv_files[0], sep="\t", comment="#", low_memory=False)
    df = df[~df["gene_id"].str.startswith("N_", na=False)]
    df = df[df["gene_id"] != "gene_id"]
    df = df.set_index("gene_id")
    expr = pd.to_numeric(df[expression_col], errors="coerce").fillna(0.0)
    return expr

# ── get top variable genes from 100 sample files ──────────────
def get_top_variable_genes(tumor_folders, healthy_folders, expression_col, top_n_genes):
    random.seed(42)
    sampled = (random.sample(tumor_folders, min(30, len(tumor_folders))) +
               random.sample(healthy_folders, min(30, len(healthy_folders))))
    series_list = []
    for folder in sampled:
        try:
            series_list.append(load_one_sample(folder, expression_col))
        except:
            pass
    df_sample = pd.DataFrame(series_list).fillna(0.0)
    top_genes = df_sample.var(axis=0).nlargest(top_n_genes).index.tolist()
    del df_sample, series_list
    gc.collect()
    print(f"Top {top_n_genes} variable genes selected from {len(sampled)} samples")
    return top_genes

# ── load all samples keeping only top genes ───────────────────
def load_all_samples_efficient(tumor_folders, healthy_folders, expression_col, top_genes):
    rows, labels = [], []
    print(f"Loading {len(tumor_folders)} tumor samples...")
    for folder in tumor_folders:
        try:
            s = load_one_sample(folder, expression_col)
            rows.append(s.reindex(top_genes, fill_value=0.0).values.astype(np.float32))
            labels.append(1)
        except Exception as e:
            print(f"  Skipping {os.path.basename(folder)}: {e}")
    print(f"Loading {len(healthy_folders)} healthy samples...")
    for folder in healthy_folders:
        try:
            s = load_one_sample(folder, expression_col)
            rows.append(s.reindex(top_genes, fill_value=0.0).values.astype(np.float32))
            labels.append(0)
        except Exception as e:
            print(f"  Skipping {os.path.basename(folder)}: {e}")
    X = np.array(rows, dtype=np.float32)
    y = np.array(labels, dtype=np.int64)
    print(f"\nLoaded: {sum(y==1)} tumor | {sum(y==0)} healthy")
    print(f"Feature matrix shape: {X.shape}")
    return X, y

# ── run ───────────────────────────────────────────────────────
torch.manual_seed(CONFIG["seed"])
np.random.seed(CONFIG["seed"])

tumor_folders   = sorted([d for d in glob.glob(os.path.join(TUMOR_DIR,   "*")) if os.path.isdir(d)])
healthy_folders = sorted([d for d in glob.glob(os.path.join(HEALTHY_DIR, "*")) if os.path.isdir(d)])

print(f"Found: {len(tumor_folders)} tumor folders | {len(healthy_folders)} healthy folders")

gene_ids = get_top_variable_genes(tumor_folders, healthy_folders,
                                   CONFIG["expression_col"], CONFIG["top_n_genes"])

X, y = load_all_samples_efficient(tumor_folders, healthy_folders,
                                   CONFIG["expression_col"], gene_ids)

# ── CELL 6: Preprocessing & splits ───────────────────────────

X = np.log1p(X)

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y,
    test_size=(CONFIG["test_size"] + CONFIG["val_size"]),
    stratify=y, random_state=CONFIG["seed"]
)
val_frac = CONFIG["val_size"] / (CONFIG["test_size"] + CONFIG["val_size"])
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp,
    test_size=(1 - val_frac),
    stratify=y_temp, random_state=CONFIG["seed"]
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train).astype(np.float32)
X_val   = scaler.transform(X_val).astype(np.float32)
X_test  = scaler.transform(X_test).astype(np.float32)

print(f"Train: {len(y_train)} | Val: {len(y_val)} | Test: {len(y_test)}")

class GenomicDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.long)

    def __len__(self):
        return len(self.y)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]


train_loader = DataLoader(GenomicDataset(X_train, y_train),
                          batch_size=CONFIG["batch_size"], shuffle=True)
val_loader   = DataLoader(GenomicDataset(X_val,   y_val),
                          batch_size=CONFIG["batch_size"], shuffle=False)
test_loader  = DataLoader(GenomicDataset(X_test,  y_test),
                          batch_size=CONFIG["batch_size"], shuffle=False)

print("DataLoaders ready")

class GenomicBERT(nn.Module):
    """
    BERT-style transformer for RNA-seq gene expression.

    Each gene is treated as one token in the sequence.
    Self-attention captures co-expression dependencies across genes —
    the same idea as DNABERT capturing dependencies across k-mers.

    The CLS-token embedding (first position) is used for classification
    and also exported for multimodal fusion with your Swin image model.
    """

    def __init__(self, n_genes: int, config: dict):
        super().__init__()
        H = config["hidden_size"]

        # Project each gene's scalar value → hidden_size vector
        self.gene_proj = nn.Linear(1, H)

        # Learnable positional embedding (one per gene position + CLS)
        self.pos_emb = nn.Embedding(n_genes + 1, H)

        self.norm = nn.LayerNorm(H)
        self.drop = nn.Dropout(config["dropout"])

        # BERT encoder
        bert_cfg = BertConfig(
            hidden_size=H,
            num_attention_heads=config["num_attention_heads"],
            num_hidden_layers=config["num_hidden_layers"],
            intermediate_size=config["intermediate_size"],
            max_position_embeddings=n_genes + 2,
            hidden_dropout_prob=config["dropout"],
            attention_probs_dropout_prob=config["dropout"],
            vocab_size=1,   # not used — we supply embeddings directly
        )
        self.encoder = BertModel(bert_cfg, add_pooling_layer=False)

        # Learnable CLS token (shared across all samples)
        self.cls_token = nn.Parameter(torch.zeros(1, 1, H))

        # Classification head
        self.head = nn.Sequential(
            nn.Linear(H, 128),
            nn.ReLU(),
            nn.Dropout(config["dropout"]),
            nn.Linear(128, 2)
        )

    def _embed(self, x):
        B, G = x.shape

        # Gene embeddings: (B, G, H)
        gene_emb = self.gene_proj(x.unsqueeze(-1))

        # Prepend CLS token: (B, G+1, H)
        cls = self.cls_token.expand(B, -1, -1)
        seq = torch.cat([cls, gene_emb], dim=1)

        # Add positional embeddings
        pos = torch.arange(G + 1, device=x.device).unsqueeze(0)
        seq = self.drop(self.norm(seq + self.pos_emb(pos)))

        return seq

    def forward(self, x):
        seq = self._embed(x)
        mask = torch.ones(seq.shape[0], seq.shape[1], device=x.device)
        out = self.encoder(inputs_embeds=seq, attention_mask=mask)
        cls_repr = out.last_hidden_state[:, 0, :]   # CLS token → classify
        return self.head(cls_repr)

    def get_embeddings(self, x):
        """Returns CLS embedding for multimodal fusion. Shape: (B, hidden_size)"""
        seq = self._embed(x)
        mask = torch.ones(seq.shape[0], seq.shape[1], device=x.device)
        out = self.encoder(inputs_embeds=seq, attention_mask=mask)
        return out.last_hidden_state[:, 0, :]


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
n_genes = X_train.shape[1]
model = GenomicBERT(n_genes, CONFIG).to(device)

n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Model ready — Trainable parameters: {n_params:,}")

counts  = np.bincount(y_train)
weights = torch.tensor([len(y_train) / (2 * c) for c in counts],
                        dtype=torch.float32).to(device)
criterion = nn.CrossEntropyLoss(weight=weights)

optimizer = torch.optim.Adam(model.parameters(), lr=CONFIG["learning_rate"])
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode="min", factor=0.5, patience=5
)

def train_one_epoch(model, loader, optimizer, criterion, device):
    model.train()
    total_loss, preds_all, labels_all = 0, [], []
    for X_b, y_b in loader:
        X_b, y_b = X_b.to(device), y_b.to(device)
        optimizer.zero_grad()
        logits = model(X_b)
        loss = criterion(logits, y_b)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        total_loss += loss.item()
        preds_all.extend(logits.argmax(1).cpu().numpy())
        labels_all.extend(y_b.cpu().numpy())
    return total_loss / len(loader), accuracy_score(labels_all, preds_all)


@torch.no_grad()
def evaluate(model, loader, criterion, device):
    model.eval()
    total_loss, preds_all, labels_all, probs_all = 0, [], [], []
    for X_b, y_b in loader:
        X_b, y_b = X_b.to(device), y_b.to(device)
        logits = model(X_b)
        total_loss += criterion(logits, y_b).item()
        probs = torch.softmax(logits, dim=1)[:, 1].cpu().numpy()
        preds_all.extend(logits.argmax(1).cpu().numpy())
        labels_all.extend(y_b.cpu().numpy())
        probs_all.extend(probs)
    return (total_loss / len(loader),
            np.array(labels_all), np.array(preds_all), np.array(probs_all))

CKPT = "/content/drive/MyDrive/genomic_best_model(1).pt"

best_val_loss  = float("inf")
patience_count = 0
history = {"train_loss": [], "val_loss": [], "train_acc": [], "val_acc": []}

print("─── Training ───────────────────────────────────────────")

for epoch in range(1, CONFIG["num_epochs"] + 1):

    tr_loss, tr_acc = train_one_epoch(model, train_loader, optimizer, criterion, device)
    vl_loss, y_val_true, y_val_pred, _ = evaluate(model, val_loader, criterion, device)
    vl_acc = accuracy_score(y_val_true, y_val_pred)

    scheduler.step(vl_loss)

    history["train_loss"].append(tr_loss)
    history["val_loss"].append(vl_loss)
    history["train_acc"].append(tr_acc)
    history["val_acc"].append(vl_acc)

    print(f"Epoch {epoch:3d}/{CONFIG['num_epochs']}  "
          f"Train Loss: {tr_loss:.4f}  Acc: {tr_acc:.4f}  |  "
          f"Val Loss: {vl_loss:.4f}  Acc: {vl_acc:.4f}")

    if vl_loss < best_val_loss:
        best_val_loss = vl_loss
        patience_count = 0
        torch.save({
            "model_state": model.state_dict(),
            "scaler": scaler,
            "gene_ids": gene_ids,
            "n_genes": n_genes,
            "config": CONFIG,
        }, CKPT)
        print(f"  ✓ Best model saved (val_loss={vl_loss:.4f})")
    else:
        patience_count += 1
        if patience_count >= CONFIG["patience"]:
            print(f"\nEarly stopping triggered at epoch {epoch}")
            break

print("\nTraining complete.")

CKPT = "/content/drive/MyDrive/genomic_best_model(1).pt"

best_val_loss  = float("inf")
patience_count = 0
history = {"train_loss": [], "val_loss": [], "train_acc": [], "val_acc": []}

print("─── Training ───────────────────────────────────────────")

for epoch in range(1, CONFIG["num_epochs"] + 1):

    tr_loss, tr_acc = train_one_epoch(model, train_loader, optimizer, criterion, device)
    vl_loss, y_val_true, y_val_pred, _ = evaluate(model, val_loader, criterion, device)
    vl_acc = accuracy_score(y_val_true, y_val_pred)

    scheduler.step(vl_loss)

    history["train_loss"].append(tr_loss)
    history["val_loss"].append(vl_loss)
    history["train_acc"].append(tr_acc)
    history["val_acc"].append(vl_acc)

    print(f"Epoch {epoch:3d}/{CONFIG['num_epochs']}  "
          f"Train Loss: {tr_loss:.4f}  Acc: {tr_acc:.4f}  |  "
          f"Val Loss: {vl_loss:.4f}  Acc: {vl_acc:.4f}")

    if vl_loss < best_val_loss:
        best_val_loss = vl_loss
        patience_count = 0
        torch.save({
            "model_state": model.state_dict(),
            "scaler": scaler,
            "gene_ids": gene_ids,
            "n_genes": n_genes,
            "config": CONFIG,
        }, CKPT)
        print(f"  ✓ Best model saved (val_loss={vl_loss:.4f})")
    else:
        patience_count += 1

print("\nTraining complete.")

ckpt = torch.load(CKPT, map_location=device, weights_only=False)
model.load_state_dict(ckpt["model_state"])

_, y_true, y_pred, y_prob = evaluate(model, test_loader, criterion, device)

print("\n─── Test Results ────────────────────────────────────────")
print(f"  Accuracy : {accuracy_score(y_true, y_pred):.4f}")
print(f"  Precision: {precision_score(y_true, y_pred, zero_division=0):.4f}")
print(f"  Recall   : {recall_score(y_true, y_pred, zero_division=0):.4f}")
print(f"  F1-Score : {f1_score(y_true, y_pred, zero_division=0):.4f}")
if len(np.unique(y_true)) > 1:
    print(f"  ROC-AUC  : {roc_auc_score(y_true, y_prob):.4f}")

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Loss curve
axes[0].plot(history["train_loss"], label="Train", color="#2196F3")
axes[0].plot(history["val_loss"],   label="Val",   color="#F44336")
axes[0].set_title("Loss")
axes[0].set_xlabel("Epoch")
axes[0].legend()
axes[0].grid(alpha=0.3)

# Accuracy curve
axes[1].plot(history["train_acc"], label="Train", color="#2196F3")
axes[1].plot(history["val_acc"],   label="Val",   color="#F44336")
axes[1].set_title("Accuracy")
axes[1].set_xlabel("Epoch")
axes[1].legend()
axes[1].grid(alpha=0.3)

# Confusion matrix
cm = confusion_matrix(y_true, y_pred)
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", ax=axes[2],
            xticklabels=["Healthy", "Tumor"],
            yticklabels=["Healthy", "Tumor"])
axes[2].set_title("Confusion Matrix")
axes[2].set_ylabel("Actual")
axes[2].set_xlabel("Predicted")

plt.tight_layout()
plt.show()

# ROC curve
if len(np.unique(y_true)) > 1:
    fpr, tpr, _ = roc_curve(y_true, y_prob)
    auc = roc_auc_score(y_true, y_prob)
    plt.figure(figsize=(6, 5))
    plt.plot(fpr, tpr, color="#2196F3", lw=2, label=f"AUC = {auc:.3f}")
    plt.plot([0, 1], [0, 1], "k--")
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title("ROC Curve — Genomic BERT")
    plt.legend()
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.show()