# -*- coding: utf-8 -*-
"""multimodel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1weNtOxmZ6qwlxYI2zT4lJzNwWuaef8fc
"""

import os
import gc
import glob
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, random_split

import torchvision
from torchvision import transforms, datasets

import timm
from transformers import BertConfig, BertModel

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, f1_score, roc_auc_score,
    precision_score, recall_score, confusion_matrix, roc_curve
)

print("All imports OK")
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "Not available — using CPU")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

import os
import gc
import glob
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, random_split

import torchvision
from torchvision import transforms, datasets

import timm
from transformers import BertConfig, BertModel

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, f1_score, roc_auc_score,
    precision_score, recall_score, confusion_matrix, roc_curve
)
from google.colab import drive
drive.mount('/content/drive')

CONFIG = {
    # ── Genomic branch ──────────────────────────────────────────
    "expression_col":       "tpm_unstranded",  # options: tpm_unstranded | fpkm_unstranded | unstranded
    "top_n_genes":          500,               # number of most-variable genes to keep

    "genomic_hidden_size":  256,
    "genomic_attn_heads":   8,
    "genomic_layers":       4,
    "genomic_intermediate": 512,
    "genomic_dropout":      0.35,

    # ── Image branch ────────────────────────────────────────────
    "swin_model":           "swin_tiny_patch4_window7_224",
    "img_size":             224,
    "swin_embed_dim":       256,               # projection dim; Swin-Tiny head → 256

    # ── Fusion ──────────────────────────────────────────────────
    "fusion_dim":           256,               # shared hidden dim after fusion
    "fusion_dropout":       0.3,
    "num_classes":          2,                 # Tumor / Healthy

    # ── Paths ───────────────────────────────────────────────────
    # Genomic data: one sub-folder per sample, each containing a *.tsv gene-expression file
    "ZIP_PATH":             "/content/drive/MyDrive/genomic_dataset.zip", # <--- Please ensure this file exists in your Google Drive or update the path.
    "DATASET_ROOT":         "/content/genomic data set",
    # Image data: ImageFolder layout  (train_OV/ → diseased/ + healthy/)
    "IMAGE_TRAIN_DIR":      "/content/drive/MyDrive/data_",
    "IMAGE_TEST_DIR":       "/content/drive/MyDrive/data_",
    # Checkpoints
    "GENOMIC_CKPT":         "/content/drive/MyDrive/genomic_best_model.pt",
    "SWIN_CKPT":            "/content/drive/MyDrive/ctranspath.pth",
    "FUSION_CKPT":          "/content/drive/MyDrive/best_fusion_model.pt",

    # ── Training ────────────────────────────────────────────────
    "batch_size":           16,
    "learning_rate":        5e-5,
    "num_epochs":           40,
    "patience":             10,
    "test_size":            0.15,
    "val_size":             0.15,
    "seed":                 42,
}

import zipfile
print("Unzipping... this takes 1-2 minutes")
with zipfile.ZipFile(CONFIG["ZIP_PATH"], 'r') as z:
    z.extractall("/content/")
print("Done unzipping")

# Correct path — extracted directly here and stored in CONFIG
CONFIG["TUMOR_DIR"]    = os.path.join(CONFIG["DATASET_ROOT"], "tumor")
CONFIG["HEALTHY_DIR"]  = os.path.join(CONFIG["DATASET_ROOT"], "healthy")

torch.manual_seed(CONFIG["seed"])
np.random.seed(CONFIG["seed"])
random.seed(CONFIG["seed"])
print("Config loaded.")

# ── helpers ──────────────────────────────────────────────────────────────
def load_one_sample(sample_dir, expression_col):
    tsv_files = glob.glob(os.path.join(sample_dir, "*.tsv"))
    if not tsv_files:
        raise FileNotFoundError(f"No TSV found in {sample_dir}")
    df = pd.read_csv(tsv_files[0], sep="\t", comment="#", low_memory=False)
    df = df[~df["gene_id"].str.startswith("N_", na=False)]
    df = df[df["gene_id"] != "gene_id"]
    df = df.set_index("gene_id")
    return pd.to_numeric(df[expression_col], errors="coerce").fillna(0.0)

def get_top_variable_genes(tumor_folders, healthy_folders, expression_col, top_n_genes):
    sampled = (random.sample(tumor_folders,   min(30, len(tumor_folders))) +
               random.sample(healthy_folders, min(30, len(healthy_folders))))
    series_list = []
    for folder in sampled:
        try:
            series_list.append(load_one_sample(folder, expression_col))
        except Exception:
            pass
    df_sample = pd.DataFrame(series_list).fillna(0.0)
    top_genes = df_sample.var(axis=0).nlargest(top_n_genes).index.tolist()
    del df_sample, series_list
    gc.collect()
    print(f"Top {top_n_genes} variable genes selected from {len(sampled)} samples.")
    return top_genes

def load_all_samples_efficient(tumor_folders, healthy_folders, expression_col, top_genes):
    rows, labels = [], []
    for folder in tumor_folders:
        try:
            s = load_one_sample(folder, expression_col)
            rows.append(s.reindex(top_genes, fill_value=0.0).values.astype(np.float32))
            labels.append(1)
        except Exception as e:
            print(f"  Skipping {os.path.basename(folder)}: {e}")
    for folder in healthy_folders:
        try:
            s = load_one_sample(folder, expression_col)
            rows.append(s.reindex(top_genes, fill_value=0.0).values.astype(np.float32))
            labels.append(0)
        except Exception as e:
            print(f"  Skipping {os.path.basename(folder)}: {e}")
    X = np.array(rows, dtype=np.float32)
    y = np.array(labels, dtype=np.int64)
    print(f"Loaded: {sum(y==1)} tumor | {sum(y==0)} healthy  |  shape: {X.shape}")
    return X, y

# ── run ────────────────────────────────────────────────────────────────────
tumor_folders   = sorted([d for d in glob.glob(os.path.join(CONFIG["TUMOR_DIR"],   "*")) if os.path.isdir(d)])
healthy_folders = sorted([d for d in glob.glob(os.path.join(CONFIG["HEALTHY_DIR"], "*")) if os.path.isdir(d)])
print(f"Tumor folders: {len(tumor_folders)}  |  Healthy folders: {len(healthy_folders)}")

gene_ids = get_top_variable_genes(tumor_folders, healthy_folders,
                                   CONFIG["expression_col"], CONFIG["top_n_genes"])
X_genomic, y_genomic = load_all_samples_efficient(tumor_folders, healthy_folders,
                                                   CONFIG["expression_col"], gene_ids)

# ── log1p transform + train/val/test split + StandardScaler ───────────────
X_genomic = np.log1p(X_genomic)

X_tr, X_tmp, y_tr, y_tmp = train_test_split(
    X_genomic, y_genomic,
    test_size=(CONFIG["test_size"] + CONFIG["val_size"]),
    stratify=y_genomic, random_state=CONFIG["seed"]
)
val_frac = CONFIG["val_size"] / (CONFIG["test_size"] + CONFIG["val_size"])
X_val_g, X_te_g, y_val_g, y_te_g = train_test_split(
    X_tmp, y_tmp, test_size=(1 - val_frac),
    stratify=y_tmp, random_state=CONFIG["seed"]
)

scaler = StandardScaler()
X_tr    = scaler.fit_transform(X_tr).astype(np.float32)
X_val_g = scaler.transform(X_val_g).astype(np.float32)
X_te_g  = scaler.transform(X_te_g).astype(np.float32)

print(f"Genomic  —  Train: {len(y_tr)} | Val: {len(y_val_g)} | Test: {len(y_te_g)}")
n_genes = X_tr.shape[1]
print(f"Feature dimension (genes): {n_genes}")

class GenomicBERT(nn.Module):

    def __init__(self, n_genes: int, config: dict):
        super().__init__()
        H = config["genomic_hidden_size"]

        self.gene_proj = nn.Linear(1, H)
        self.pos_emb   = nn.Embedding(n_genes + 1, H)
        self.norm      = nn.LayerNorm(H)
        self.drop      = nn.Dropout(config["genomic_dropout"])

        bert_cfg = BertConfig(
            hidden_size              = H,
            num_attention_heads      = config["genomic_attn_heads"],
            num_hidden_layers        = config["genomic_layers"],
            intermediate_size        = config["genomic_intermediate"],
            max_position_embeddings  = n_genes + 2,
            hidden_dropout_prob      = config["genomic_dropout"],
            attention_probs_dropout_prob = config["genomic_dropout"],
            vocab_size               = 1,
        )
        self.encoder   = BertModel(bert_cfg, add_pooling_layer=False)
        self.cls_token = nn.Parameter(torch.zeros(1, 1, H))

        # standalone head (used when training genomic branch alone)
        self.head = nn.Sequential(
            nn.Linear(H, 128), nn.ReLU(),
            nn.Dropout(config["genomic_dropout"]),
            nn.Linear(128, config["num_classes"])
        )

    def _embed(self, x):
        B, G = x.shape
        gene_emb = self.gene_proj(x.unsqueeze(-1))              # (B, G, H)
        cls      = self.cls_token.expand(B, -1, -1)             # (B, 1, H)
        seq      = torch.cat([cls, gene_emb], dim=1)            # (B, G+1, H)
        pos      = torch.arange(G + 1, device=x.device).unsqueeze(0)
        seq      = self.drop(self.norm(seq + self.pos_emb(pos)))
        return seq

    def forward(self, x):
        seq  = self._embed(x)
        mask = torch.ones(seq.shape[0], seq.shape[1], device=x.device)
        out  = self.encoder(inputs_embeds=seq, attention_mask=mask)
        return self.head(out.last_hidden_state[:, 0, :])

    def get_embedding(self, x):
        """Returns CLS embedding (B, hidden_size) for fusion."""
        seq  = self._embed(x)
        mask = torch.ones(seq.shape[0], seq.shape[1], device=x.device)
        out  = self.encoder(inputs_embeds=seq, attention_mask=mask)
        return out.last_hidden_state[:, 0, :]          # (B, H)

class SwinEncoder(nn.Module):
    """
    Wraps timm's Swin-Tiny.  Removes the classification head and projects
    the 768-d pooled feature to `swin_embed_dim` (default 256) so both
    modality embeddings share the same dimensionality going into fusion.
    """
    def __init__(self, config: dict, pretrained: bool = True):
        super().__init__()
        backbone = timm.create_model(
            config["swin_model"],
            pretrained  = pretrained,
            num_classes = 0,          # remove classification head → returns pooled features
        )
        # Swin-Tiny outputs 768-d after global average pooling
        swin_out_dim = backbone.num_features
        self.backbone = backbone
        self.proj = nn.Sequential(
            nn.Linear(swin_out_dim, config["swin_embed_dim"]),
            nn.LayerNorm(config["swin_embed_dim"]),
        )

    def forward(self, x):
        """x: (B, 3, H, W) → (B, swin_embed_dim)"""
        feats = self.backbone(x)      # (B, 768)
        return self.proj(feats)       # (B, 256)

class GatedFusion(nn.Module):
    """
    Learnable gating that weights each modality per-sample before summing.

    Given genomic embedding g ∈ R^D and image embedding v ∈ R^D:
        gate_g = σ(W_g · [g, v])
        gate_v = σ(W_v · [g, v])
        fused  = gate_g * g  +  gate_v * v

    This lets the model learn to rely more on whichever modality is
    informative for a given patient.
    """
    def __init__(self, dim: int):
        super().__init__()
        self.gate_g = nn.Linear(dim * 2, dim)
        self.gate_v = nn.Linear(dim * 2, dim)

    def forward(self, g, v):
        """g, v: (B, D) → fused: (B, D)"""
        cat    = torch.cat([g, v], dim=-1)          # (B, 2D)
        alpha  = torch.sigmoid(self.gate_g(cat))    # (B, D)
        beta   = torch.sigmoid(self.gate_v(cat))    # (B, D)
        return alpha * g + beta * v                 # (B, D)


class MultimodalFusionModel(nn.Module):
    """
    End-to-end fusion of GenomicBERT + SwinEncoder.

    Forward:
        gene_x  : (B, n_genes)   — scaled log1p gene expression
        image_x : (B, 3, 224, 224) — normalised histopathology patch
    Returns:
        logits  : (B, num_classes)
    """
    def __init__(self, n_genes: int, config: dict, pretrained_swin: bool = True):
        super().__init__()
        D = config["fusion_dim"]

        self.genomic_encoder = GenomicBERT(n_genes, config)
        self.image_encoder   = SwinEncoder(config, pretrained=pretrained_swin)
        self.fusion          = GatedFusion(D)

        self.classifier = nn.Sequential(
            nn.LayerNorm(D),
            nn.Linear(D, 128),
            nn.GELU(),
            nn.Dropout(config["fusion_dropout"]),
            nn.Linear(128, config["num_classes"])
        )

    def forward(self, gene_x, image_x):
        g_emb  = self.genomic_encoder.get_embedding(gene_x)    # (B, D)
        v_emb  = self.image_encoder(image_x)                    # (B, D)
        fused  = self.fusion(g_emb, v_emb)                      # (B, D)
        return self.classifier(fused)                           # (B, num_classes)

    def load_pretrained_branches(self, genomic_ckpt_path: str = None,
                                  swin_ckpt_path: str = None):
        """
        Optionally warm-start individual branches from their solo checkpoints.
        Skips loading if a path is None or the file doesn't exist.
        """
        if genomic_ckpt_path and os.path.exists(genomic_ckpt_path):
            ckpt = torch.load(genomic_ckpt_path, map_location="cpu", weights_only=False)
            state = ckpt.get("model_state", ckpt)
            # filter to keys that belong to genomic_encoder
            filtered = {k: v for k, v in state.items()
                        if not k.startswith("head.")}
            self.genomic_encoder.load_state_dict(filtered, strict=False)
            print(f"✓ Loaded GenomicBERT weights from {genomic_ckpt_path}")
        if swin_ckpt_path and os.path.exists(swin_ckpt_path):
            state = torch.load(swin_ckpt_path, map_location="cpu", weights_only=False)
            # Swin checkpoint saved as raw state_dict (no wrapper)
            self.image_encoder.backbone.load_state_dict(state, strict=False)
            print(f"✓ Loaded SwinTransformer weights from {swin_ckpt_path}")

class MultimodalDataset(Dataset):
    """
    Pairs a genomic vector with a randomly sampled image from the same class.

    In a real deployment you would pair samples by patient/slide ID.
    Here we fall back to class-level pairing when 1-to-1 IDs are not
    available — samples are drawn with replacement so every genomic sample
    gets an image partner at each epoch.

    Args:
        gene_X     : np.ndarray (N_g, n_genes)
        gene_y     : np.ndarray (N_g,)
        image_root : str — path to ImageFolder-style directory
        transform  : torchvision transform for images
    """
    def __init__(self, gene_X, gene_y, image_root, transform=None):
        self.gene_X    = torch.tensor(gene_X, dtype=torch.float32)
        self.gene_y    = torch.tensor(gene_y, dtype=torch.long)
        self.transform = transform

        # Build class → [image_paths] index
        self.class_images = {}
        for class_name in os.listdir(image_root):
            class_dir = os.path.join(image_root, class_name)
            if not os.path.isdir(class_dir):
                continue
            imgs = [os.path.join(class_dir, f) for f in os.listdir(class_dir)
                    if f.lower().endswith((".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff"))]
            if imgs:
                self.class_images[class_name] = imgs

        # Map label index → class name (assumes ImageFolder ordering: alphabetical)
        self.idx_to_class = {i: c for i, c in enumerate(sorted(self.class_images.keys()))}
        print(f"Image classes: {self.idx_to_class}")
        print(f"Genomic samples: {len(self.gene_y)}")

    def __len__(self):
        return len(self.gene_y)

    def __getitem__(self, idx):
        gene_vec = self.gene_X[idx]
        label    = self.gene_y[idx].item()

        # sample a matching-class image
        class_name = self.idx_to_class.get(label)
        img_paths  = self.class_images.get(class_name, [])
        if img_paths:
            img_path = random.choice(img_paths)
            try:
                img = Image.open(img_path).convert("RGB")
            except Exception:
                img = Image.new("RGB", (224, 224))
        else:
            img = Image.new("RGB", (224, 224))

        if self.transform:
            img = self.transform(img)

        return gene_vec, img, torch.tensor(label, dtype=torch.long)


# ── Image transforms ──────────────────────────────────────────────────────
train_transform = transforms.Compose([
    transforms.RandomResizedCrop(CONFIG["img_size"], scale=(0.8, 1.0)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomVerticalFlip(),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.1),
    transforms.ToTensor(),
    transforms.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5)),
])

val_transform = transforms.Compose([
    transforms.Resize((CONFIG["img_size"], CONFIG["img_size"])),
    transforms.ToTensor(),
    transforms.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5)),
])

# ── Build datasets & loaders ──────────────────────────────────────────────
train_ds = MultimodalDataset(X_tr,    y_tr,    CONFIG["IMAGE_TRAIN_DIR"], train_transform)
val_ds   = MultimodalDataset(X_val_g, y_val_g, CONFIG["IMAGE_TRAIN_DIR"], val_transform)
test_ds  = MultimodalDataset(X_te_g,  y_te_g,  CONFIG["IMAGE_TEST_DIR"],  val_transform)

train_loader_mm = DataLoader(train_ds, batch_size=CONFIG["batch_size"], shuffle=True,  num_workers=2, pin_memory=True)
val_loader_mm   = DataLoader(val_ds,   batch_size=CONFIG["batch_size"], shuffle=False, num_workers=2, pin_memory=True)
test_loader_mm  = DataLoader(test_ds,  batch_size=CONFIG["batch_size"], shuffle=False, num_workers=2, pin_memory=True)

print(f"DataLoaders ready — Train batches: {len(train_loader_mm)} | Val: {len(val_loader_mm)} | Test: {len(test_loader_mm)}")

fusion_model = MultimodalFusionModel(n_genes=n_genes, config=CONFIG, pretrained_swin=True).to(device)

# ── Optional: warm-start branches from solo checkpoints ──────────────────
# Comment these out if you want to train the fusion model end-to-end from scratch.
fusion_model.load_pretrained_branches(
    genomic_ckpt_path = CONFIG["GENOMIC_CKPT"],
    swin_ckpt_path    = CONFIG["SWIN_CKPT"],
)

n_params = sum(p.numel() for p in fusion_model.parameters() if p.requires_grad)
print(f"\nFusion model — trainable parameters: {n_params:,}")

# ── Class-weighted loss ───────────────────────────────────────────────────
counts  = np.bincount(y_tr)
weights = torch.tensor([len(y_tr) / (2 * c) for c in counts], dtype=torch.float32).to(device)
criterion = nn.CrossEntropyLoss(weight=weights)

# ── Optimizer: lower LR for pretrained backbones, higher for fusion head ──
backbone_params = (list(fusion_model.genomic_encoder.parameters()) +
                   list(fusion_model.image_encoder.parameters()))
head_params     = (list(fusion_model.fusion.parameters()) +
                   list(fusion_model.classifier.parameters()))

optimizer = optim.AdamW([
    {"params": backbone_params, "lr": CONFIG["learning_rate"] * 0.1},
    {"params": head_params,     "lr": CONFIG["learning_rate"]},
], weight_decay=1e-4)

scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=CONFIG["num_epochs"])
print("Optimizer & scheduler ready.")

def train_one_epoch_mm(model, loader, optimizer, criterion, device):
    model.train()
    total_loss, preds_all, labels_all = 0.0, [], []
    for gene_x, img_x, y_b in loader:
        gene_x, img_x, y_b = gene_x.to(device), img_x.to(device), y_b.to(device)
        optimizer.zero_grad()
        logits = model(gene_x, img_x)
        loss   = criterion(logits, y_b)
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        total_loss += loss.item()
        preds_all.extend(logits.argmax(1).cpu().numpy())
        labels_all.extend(y_b.cpu().numpy())
    return total_loss / len(loader), accuracy_score(labels_all, preds_all)


@torch.no_grad()
def evaluate_mm(model, loader, criterion, device):
    model.eval()
    total_loss, preds_all, labels_all, probs_all = 0.0, [], [], []
    for gene_x, img_x, y_b in loader:
        gene_x, img_x, y_b = gene_x.to(device), img_x.to(device), y_b.to(device)
        logits = model(gene_x, img_x)
        total_loss += criterion(logits, y_b).item()
        probs = F.softmax(logits, dim=1)[:, 1].cpu().numpy()
        preds_all.extend(logits.argmax(1).cpu().numpy())
        labels_all.extend(y_b.cpu().numpy())
        probs_all.extend(probs)
    return (total_loss / len(loader),
            np.array(labels_all), np.array(preds_all), np.array(probs_all))

best_val_loss  = float("inf")
patience_count = 0
history = {"train_loss": [], "val_loss": [], "train_acc": [], "val_acc": []}

print("─── Multimodal Fusion Training ──────────────────────────────────────")
print(f"{'Epoch':>6}  {'Tr Loss':>8}  {'Tr Acc':>7}  {'Vl Loss':>8}  {'Vl Acc':>7}")
print("─" * 55)

for epoch in range(1, CONFIG["num_epochs"] + 1):
    tr_loss, tr_acc = train_one_epoch_mm(fusion_model, train_loader_mm, optimizer, criterion, device)
    vl_loss, y_vt, y_vp, _ = evaluate_mm(fusion_model, val_loader_mm, criterion, device)
    vl_acc = accuracy_score(y_vt, y_vp)
    scheduler.step()

    history["train_loss"].append(tr_loss)
    history["val_loss"].append(vl_loss)
    history["train_acc"].append(tr_acc)
    history["val_acc"].append(vl_acc)

    print(f"{epoch:6d}  {tr_loss:8.4f}  {tr_acc:7.4f}  {vl_loss:8.4f}  {vl_acc:7.4f}")

    if vl_loss < best_val_loss:
        best_val_loss = vl_loss
        patience_count = 0
        torch.save({
            "model_state": fusion_model.state_dict(),
            "optimizer":   optimizer.state_dict(),
            "config":      CONFIG,
            "gene_ids":    gene_ids,
            "n_genes":     n_genes,
            "scaler":      scaler,
            "epoch":       epoch,
        }, CONFIG["FUSION_CKPT"])
        print(f"  ✓ Best model saved (val_loss={vl_loss:.4f})")
    else:
        patience_count += 1
        if patience_count >= CONFIG["patience"]:
            print(f"\nEarly stopping at epoch {epoch} (no improvement for {CONFIG['patience']} epochs).")
            break

print("\nTraining complete.")

# ── Load best checkpoint ──────────────────────────────────────────────────
ckpt = torch.load(CONFIG["FUSION_CKPT"], map_location=device, weights_only=False)
fusion_model.load_state_dict(ckpt["model_state"])
print(f"Loaded best checkpoint from epoch {ckpt.get('epoch', '?')}")

_, y_true, y_pred, y_prob = evaluate_mm(fusion_model, test_loader_mm, criterion, device)

print("\n─── Test Results ─────────────────────────────────────────────────────")
print(f"  Accuracy  : {accuracy_score(y_true, y_pred):.4f}")
print(f"  Precision : {precision_score(y_true, y_pred, zero_division=0):.4f}")
print(f"  Recall    : {recall_score(y_true, y_pred, zero_division=0):.4f}")
print(f"  F1-Score  : {f1_score(y_true, y_pred, zero_division=0):.4f}")
if len(np.unique(y_true)) > 1:
    print(f"  ROC-AUC   : {roc_auc_score(y_true, y_prob):.4f}")

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

axes[0].plot(history["train_loss"], label="Train", color="#2196F3")
axes[0].plot(history["val_loss"],   label="Val",   color="#F44336")
axes[0].set_title("Fusion Model — Loss")
axes[0].set_xlabel("Epoch"); axes[0].legend(); axes[0].grid(alpha=0.3)

axes[1].plot(history["train_acc"], label="Train", color="#2196F3")
axes[1].plot(history["val_acc"],   label="Val",   color="#F44336")
axes[1].set_title("Fusion Model — Accuracy")
axes[1].set_xlabel("Epoch"); axes[1].legend(); axes[1].grid(alpha=0.3)

cm = confusion_matrix(y_true, y_pred)
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", ax=axes[2],
            xticklabels=["Healthy", "Tumor"],
            yticklabels=["Healthy", "Tumor"])
axes[2].set_title("Confusion Matrix"); axes[2].set_ylabel("Actual"); axes[2].set_xlabel("Predicted")

plt.suptitle("Multimodal Fusion: GenomicBERT + Swin Transformer", fontsize=14, fontweight="bold")
plt.tight_layout()
plt.show()

# ── ROC curve ─────────────────────────────────────────────────────────────
if len(np.unique(y_true)) > 1:
    fpr, tpr, _ = roc_curve(y_true, y_prob)
    auc = roc_auc_score(y_true, y_prob)
    plt.figure(figsize=(6, 5))
    plt.plot(fpr, tpr, color="#2196F3", lw=2, label=f"Fusion AUC = {auc:.3f}")
    plt.plot([0, 1], [0, 1], "k--")
    plt.xlabel("False Positive Rate"); plt.ylabel("True Positive Rate")
    plt.title("ROC Curve — Multimodal Fusion Model")
    plt.legend(); plt.grid(alpha=0.3); plt.tight_layout(); plt.show()

@torch.no_grad()
def predict_single(model, gene_vector: np.ndarray, image_path: str,
                   scaler, transform, device, class_names=("Healthy", "Tumor")):
    """
    Predict the class of one patient given:
      - gene_vector : raw gene-expression array of shape (n_genes,) — BEFORE log1p / scaling
      - image_path  : path to a histopathology image
    """
    model.eval()

    # Preprocess genomic
    gene_log = np.log1p(gene_vector).reshape(1, -1).astype(np.float32)
    gene_sc  = scaler.transform(gene_log)
    gene_t   = torch.tensor(gene_sc, dtype=torch.float32).to(device)

    # Preprocess image
    img = Image.open(image_path).convert("RGB")
    img_t = transform(img).unsqueeze(0).to(device)           # (1, 3, H, W)

    logits = model(gene_t, img_t)
    probs  = F.softmax(logits, dim=1).squeeze().cpu().numpy()
    pred   = probs.argmax()

    print(f"Prediction : {class_names[pred]}  (confidence: {probs[pred]:.3f})")
    print(f"Class probs: { {n: f'{p:.3f}' for n, p in zip(class_names, probs)} }")
    return pred, probs


# ── Example usage (replace paths with real data) ───────────────────────────
# dummy_gene_vec = np.random.rand(n_genes).astype(np.float32)
# predict_single(fusion_model, dummy_gene_vec, "/path/to/slide.png",
#                scaler, val_transform, device)
print("predict_single() helper defined — ready for inference.")