# -*- coding: utf-8 -*-
"""multimodal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/142GLfVkLDnwblY7xBVETg2eDLl9OG8xl
"""

!pip install timm transformers torch torchvision

import torch
import torch.nn as nn
from torchvision import transforms
from PIL import Image
import timm
from transformers import AutoTokenizer, AutoModel

#train and test data directory
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')
model_path = '/content/drive/MyDrive/best_swin_model.pth'

import torch
import torch.nn as nn
import timm

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Load trained Swin
swin = timm.create_model(
    'swin_base_patch4_window7_224',
    pretrained=False,
    num_classes=2
)

checkpoint = torch.load('/content/drive/MyDrive/best_swin_model.pth', map_location=device)

if 'model_state_dict' in checkpoint:
    swin.load_state_dict(checkpoint['model_state_dict'])
else:
    swin.load_state_dict(checkpoint)

# REMOVE classifier
swin.head = nn.Identity()

swin = swin.to(device)
swin.eval()

from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained("zhihan1996/DNA_bert_6")
dnabert = AutoModel.from_pretrained("zhihan1996/DNA_bert_6")

dnabert = dnabert.to(device)
dnabert.eval()

class MultimodalClassifier(nn.Module):
    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(1024 + 768, 512)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(0.3)
        self.fc2 = nn.Linear(512, 2)

    def forward(self, img_feat, dna_feat):
        combined = torch.cat((img_feat, dna_feat), dim=1)
        x = self.fc1(combined)
        x = self.relu(x)
        x = self.dropout(x)
        output = self.fc2(x)
        return output

model = MultimodalClassifier().to(device)

# ================================
# STEP 0 — Install & Imports
# ================================

!pip install -q transformers

import torch
from transformers import AutoTokenizer, AutoModel



# ================================
# STEP 1 — k-mer Conversion Function
# ================================

def dna_to_kmers(sequence, k=6):
    return [sequence[i:i+k] for i in range(len(sequence) - k + 1)]


# ================================
# STEP 2 — Load DNABERT Tokenizer & Model
# ================================

tokenizer = AutoTokenizer.from_pretrained("zhihan1996/DNA_bert_6")
dnabert = AutoModel.from_pretrained("zhihan1996/DNA_bert_6").to(device)
dnabert.eval()

print("\nDNABERT Loaded Successfully\n")


# ================================
# STEP 3 — Define Sample DNA Sequences
# ================================

sample_sequences = [
    "ATCGTACGATCGATCGATCG",
    "CGTACGTAGCTAGCTAGCTA",
    "TTGCGATCGATCGTACGATC"
]


# ================================
# STEP 4 — Validate Full Pipeline
# ================================

for idx, sequence in enumerate(sample_sequences):

    print("="*60)
    print(f"Processing Sequence {idx+1}")
    print("Raw DNA:", sequence)

    # ---- k-mer Conversion ----
    kmers = dna_to_kmers(sequence, k=6)

    print("\nOriginal Length:", len(sequence))
    print("Number of k-mers:", len(kmers))
    print("First 5 k-mers:", kmers[:5])

    # Mathematical validation
    expected_kmers = len(sequence) - 6 + 1
    print("Expected k-mers (L-k+1):", expected_kmers)

    # ---- Convert to DNABERT format ----
    dna_string = " ".join(kmers)

    # ---- Tokenization ----
    inputs = tokenizer(dna_string, return_tensors="pt", truncation=True)

    print("\nTokenizer Keys:", inputs.keys())
    print("Input ID Shape:", inputs["input_ids"].shape)

    # Move to GPU/CPU
    inputs = {k: v.to(device) for k, v in inputs.items()}

    # ---- Transformer Forward Pass ----
    with torch.no_grad():
        outputs = dnabert(**inputs)

    print("Last Hidden State Shape:", outputs.last_hidden_state.shape)

    # ---- Mean Pooling ----
    dna_features = outputs.last_hidden_state.mean(dim=1)

    print("Final Genomic Feature Vector Shape:", dna_features.shape)
    print("="*60, "\n")


print("✅ GENOMIC PIPELINE VALIDATED SUCCESSFULLY")

# ============================================
# PHASE 3 — DNABERT TRANSFORMER VALIDATION
# ============================================

# Install transformers (if not already installed)
!pip install -q transformers

import torch
from transformers import AutoTokenizer, AutoModel

# --------------------------------------------
# Step 1 — Device Setup
# --------------------------------------------
# This ensures model runs on GPU if available

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)


# --------------------------------------------
# Step 2 — Load DNABERT Tokenizer and Model
# --------------------------------------------
# Tokenizer converts k-mers → token IDs
# Model converts token IDs → contextual embeddings

tokenizer = AutoTokenizer.from_pretrained("zhihan1996/DNA_bert_6")
dnabert = AutoModel.from_pretrained("zhihan1996/DNA_bert_6").to(device)

dnabert.eval()  # evaluation mode (no dropout)


# --------------------------------------------
# Step 3 — Sample DNA Sequence
# --------------------------------------------
sample_dna = "ATCGTACGATCGATCGATCG"

print("\nRaw DNA Sequence:")
print(sample_dna)


# --------------------------------------------
# Step 4 — Convert to 6-mers
# --------------------------------------------
def dna_to_kmers(sequence, k=6):
    return [sequence[i:i+k] for i in range(len(sequence) - k + 1)]

kmers = dna_to_kmers(sample_dna, k=6)
dna_string = " ".join(kmers)

print("\nFirst 5 k-mers:", kmers[:5])
print("Total k-mers:", len(kmers))


# --------------------------------------------
# Step 5 — Tokenization
# --------------------------------------------
# Converts string into numerical token IDs

inputs = tokenizer(dna_string, return_tensors="pt", truncation=True)

print("\nTokenizer Output Keys:", inputs.keys())
print("Input ID Shape:", inputs["input_ids"].shape)

# Move tensors to GPU/CPU
inputs = {k: v.to(device) for k, v in inputs.items()}


# --------------------------------------------
# Step 6 — Transformer Forward Pass
# --------------------------------------------
# This is the critical validation step.
# We pass input IDs into DNABERT.

with torch.no_grad():
    outputs = dnabert(**inputs)

# DNABERT returns:
# last_hidden_state → contextual embedding for each token

print("\nLast Hidden State Shape:")
print(outputs.last_hidden_state.shape)


# --------------------------------------------
# Step 7 — Validate Embedding Dimension
# --------------------------------------------
# Shape format:
# [batch_size, sequence_length, hidden_dimension]

batch_size, seq_len, hidden_dim = outputs.last_hidden_state.shape

print("\nBatch Size:", batch_size)
print("Sequence Length:", seq_len)
print("Hidden Dimension:", hidden_dim)

# Confirm hidden dimension is 768
if hidden_dim == 768:
    print("\n✅ DNABERT embedding dimension is correct (768)")
else:
    print("\n❌ Unexpected embedding dimension")

# ============================================
# PHASE 4 — VALIDATE EMBEDDING POOLING
# ============================================

!pip install -q transformers

import torch
from transformers import AutoTokenizer, AutoModel

# --------------------------------------------
# Step 1 — Device Setup
# --------------------------------------------
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# --------------------------------------------
# Step 2 — Load DNABERT
# --------------------------------------------
tokenizer = AutoTokenizer.from_pretrained("zhihan1996/DNA_bert_6")
dnabert = AutoModel.from_pretrained("zhihan1996/DNA_bert_6").to(device)
dnabert.eval()

# --------------------------------------------
# Step 3 — Sample DNA
# --------------------------------------------
sample_dna = "ATCGTACGATCGATCGATCG"

def dna_to_kmers(sequence, k=6):
    return [sequence[i:i+k] for i in range(len(sequence) - k + 1)]

kmers = dna_to_kmers(sample_dna, k=6)
dna_string = " ".join(kmers)

# --------------------------------------------
# Step 4 — Tokenization
# --------------------------------------------
inputs = tokenizer(dna_string, return_tensors="pt", truncation=True)
inputs = {k: v.to(device) for k, v in inputs.items()}

# --------------------------------------------
# Step 5 — Transformer Forward Pass
# --------------------------------------------
with torch.no_grad():
    outputs = dnabert(**inputs)

# This is token-level embedding
token_embeddings = outputs.last_hidden_state

print("\nToken-level Embedding Shape:")
print(token_embeddings.shape)

# Expected shape:
# [batch_size, sequence_length, 768]


# --------------------------------------------
# Step 6 — Apply Mean Pooling
# --------------------------------------------
# We reduce across sequence_length dimension (dim=1)

pooled_embedding = token_embeddings.mean(dim=1)

print("\nAfter Mean Pooling:")
print(pooled_embedding.shape)

# Expected shape:
# [batch_size, 768]


# --------------------------------------------
# Step 7 — Validate Fixed-Length Representation
# --------------------------------------------
batch_size, hidden_dim = pooled_embedding.shape

print("\nBatch Size:", batch_size)
print("Final Feature Dimension:", hidden_dim)

if hidden_dim == 768:
    print("\n✅ Fixed-length 768-dimensional genomic feature vector generated")
else:
    print("\n❌ Unexpected feature dimension")

!pip install -q timm transformers

import torch
import torch.nn as nn
import timm
from transformers import AutoTokenizer, AutoModel
from torchvision import transforms
from PIL import Image

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# --------------------------------------------
# Step 1 — Load Swin (Image Feature Extractor)
# --------------------------------------------

swin = timm.create_model(
    'swin_base_patch4_window7_224',
    pretrained=False,
    num_classes=2
)

checkpoint = torch.load('/content/drive/MyDrive/best_swin_model.pth', map_location=device)

if 'model_state_dict' in checkpoint:
    swin.load_state_dict(checkpoint['model_state_dict'])
else:
    swin.load_state_dict(checkpoint)

# Remove classification head → we want features only
swin.head = nn.Identity()
swin = swin.to(device)
swin.eval()

print("Swin loaded and classifier removed.\n")


# --------------------------------------------
# Step 2 — Load DNABERT (Genomic Feature Extractor)
# --------------------------------------------

tokenizer = AutoTokenizer.from_pretrained("zhihan1996/DNA_bert_6")
dnabert = AutoModel.from_pretrained("zhihan1996/DNA_bert_6").to(device)
dnabert.eval()

print("DNABERT loaded.\n")


# --------------------------------------------
# Step 3 — Extract Image Feature
# --------------------------------------------

transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
])

# Replace with a real image path from your dataset
image_path = "/content/drive/MyDrive/test_OV/diseased/ol (37).png"

image = Image.open(image_path).convert("RGB")
image = transform(image).unsqueeze(0).to(device)

with torch.no_grad():
    img_feat = swin(image)

print("Image Feature Shape:", img_feat.shape)
# Expected → [1, 1024]


# --------------------------------------------
# Step 4 — Extract Genomic Feature
# --------------------------------------------

def dna_to_kmers(sequence, k=6):
    return [sequence[i:i+k] for i in range(len(sequence) - k + 1)]

sample_dna = "ATCGTACGATCGATCGATCG"

kmers = dna_to_kmers(sample_dna)
dna_string = " ".join(kmers)

inputs = tokenizer(dna_string, return_tensors="pt", truncation=True)
inputs = {k: v.to(device) for k, v in inputs.items()}

with torch.no_grad():
    outputs = dnabert(**inputs)

dna_feat = outputs.last_hidden_state.mean(dim=1)

print("Genomic Feature Shape:", dna_feat.shape)
# Expected → [1, 768]

# --------------------------------------------
# Step 5 — Define Fusion Model
# --------------------------------------------

class MultimodalFusion(nn.Module):
    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(1024 + 768, 512)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(0.3)
        self.fc2 = nn.Linear(512, 2)

    def forward(self, img_feat, dna_feat):
        # Ensure img_feat is flattened to [batch_size, feature_dim] if it has spatial dimensions
        if img_feat.dim() == 4: # Assuming format [batch_size, H, W, C]
            img_feat = img_feat.mean(dim=(-2, -3)) # Global Average Pooling

        # Concatenate along feature dimension
        combined = torch.cat((img_feat, dna_feat), dim=1)

        print("Combined Feature Shape:", combined.shape)
        # Expected → [1, 1792]

        x = self.fc1(combined)
        x = self.relu(x)
        x = self.dropout(x)
        output = self.fc2(x)

        return output


fusion_model = MultimodalFusion().to(device)
fusion_model.eval()


# --------------------------------------------
# Step 6 — Validate Fusion Forward Pass
# --------------------------------------------

with torch.no_grad():
    output = fusion_model(img_feat, dna_feat)

print("Final Output Shape:", output.shape)
# Expected → [1, 2]

# Convert to probabilities
probabilities = torch.softmax(output, dim=1)
print("Prediction Probabilities:", probabilities)