# -*- coding: utf-8 -*-
"""swin_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nfn_bnMzbFrUnYNSh2nesbbqMNqLgSbJ
"""

!pip install pydicom timm torch torchvision numpy scikit-learn matplotlib seaborn tqdm

import os
import glob
import random
import numpy as np
import pydicom
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import timm
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import (
    accuracy_score, f1_score, roc_auc_score,
    confusion_matrix, roc_curve
)
from sklearn.model_selection import train_test_split
from tqdm import tqdm

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device: {device}')
if torch.cuda.is_available():
    print(f'GPU: {torch.cuda.get_device_name(0)}')

from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

healthy_extract = "/content/drive/MyDrive/healthy"
disease_extract = "/content/drive/MyDrive/diseased"

import glob
import pydicom

def find_axial_series(patient_dir):
    all_dcm = glob.glob(
        os.path.join(patient_dir, '**', '*.dcm'),
        recursive=True
    )

    series_dict = {}

    for dcm_path in all_dcm:
        try:
            ds = pydicom.dcmread(dcm_path, stop_before_pixels=True)

            series_uid = str(getattr(ds, 'SeriesInstanceUID', 'unknown'))

            image_type = list(getattr(ds, 'ImageType', []))
            if 'LOCALIZER' in image_type or 'SCOUT' in image_type:
                continue

            desc = str(getattr(ds, 'SeriesDescription', '')).upper()

            # Skip non-axial
            if any(x in desc for x in ['CORONAL', 'SAGITTAL', 'MPR', 'REFORMAT']):
                continue

            if series_uid not in series_dict:
                series_dict[series_uid] = []

            series_dict[series_uid].append(dcm_path)

        except:
            continue

    if not series_dict:
        return all_dcm

    best_series = max(series_dict.values(), key=len)
    return sorted(best_series)

import numpy as np

def get_hu_image(dcm):
    img = dcm.pixel_array.astype(np.float32)

    slope = getattr(dcm, "RescaleSlope", 1)
    intercept = getattr(dcm, "RescaleIntercept", 0)

    return img * slope + intercept


def is_pelvic_slice(dcm):
    hu = get_hu_image(dcm)

    # Tissue + bone region
    mask = (hu > -200) & (hu < 300)

    ratio = np.sum(mask) / mask.size

    return ratio > 0.15

MAX_SLICES = 64

def sample_slices(dcm_files):
    if len(dcm_files) <= MAX_SLICES:
        return dcm_files

    step = len(dcm_files) // MAX_SLICES
    return dcm_files[::step][:MAX_SLICES]

import shutil
from tqdm import tqdm

healthy_root = os.path.join(healthy_extract, "health")
healthy_output = "/content/drive/MyDrive/dataset/health"

os.makedirs(healthy_output, exist_ok=True)

count_h = 0

for patient in tqdm(os.listdir(healthy_root)):
    patient_path = os.path.join(healthy_root, patient)

    if not os.path.isdir(patient_path):
        continue

    try:
        # 🔥 NEW: automatically get best axial series
        axial_files = find_axial_series(patient_path)

        if len(axial_files) < 10: continue
        if len(pelvic_files) < 5: continue

        pelvic_files = []

        for dcm_path in axial_files:
            try:
                dcm = pydicom.dcmread(dcm_path)

                if is_pelvic_slice(dcm):
                    pelvic_files.append(dcm_path)

            except:
                continue

        if len(pelvic_files) < 20:
            continue

        save_path = os.path.join(healthy_output, patient)
        os.makedirs(save_path, exist_ok=True)

        for f in pelvic_files:
            shutil.copy2(f, os.path.join(save_path, os.path.basename(f)))

        count_h += 1

    except:
        continue

print("✅ Healthy processed:", count_h)

disease_root = os.path.join(disease_extract, "disease")
disease_output = "/content/drive/MyDrive/dataset/diseased"

os.makedirs(disease_output, exist_ok=True)

count_d = 0

for patient in tqdm(os.listdir(disease_root)):
    patient_path = os.path.join(disease_root, patient)

    if not os.path.isdir(patient_path):
        continue

    all_dcm = glob.glob(
        os.path.join(patient_path, '**', '*.dcm'),
        recursive=True
    )

    if len(all_dcm) < 20:
        continue

    save_path = os.path.join(disease_output, patient)
    os.makedirs(save_path, exist_ok=True)

    for f in all_dcm:
        shutil.copy2(f, os.path.join(save_path, os.path.basename(f)))

    count_d += 1

print("✅ Diseased processed:", count_d)

def count_dicoms(path):
    total = 0
    for root, _, files in os.walk(path):
        total += len([f for f in files if f.endswith(".dcm")])
    return total

print("Healthy slices:", count_dicoms("/content/MyDrive/dataset/healthy"))
print("Diseased slices:", count_dicoms("/content/MyDrive/dataset/diseased"))

import random
import os

def get_all_files(path):
    files = []
    for root, _, f in os.walk(path):
        for file in f:
            if file.endswith(".dcm"):
                files.append(os.path.join(root, file))
    return files

healthy_files = get_all_files("/content/MyDrive/dataset/healthy")
diseased_files = get_all_files("/content/MyDrive/dataset/diseased")

min_count = min(len(healthy_files), len(diseased_files))

healthy_files = random.sample(healthy_files, min_count)
diseased_files = random.sample(diseased_files, min_count)

print("Balanced count:", min_count)

CONFIG = {
    # ── Paths ──────────────────────────────────────────────────
    'DISEASED_DIR': '/content/drive/MyDrive/data/diseased',   # TCGA-OV
    'HEALTHY_DIR':  '/content/drive/MyDrive/data/healthy',    # Healthy-Total-Body-CTs
    'CKPT_PATH':    '/content/drive/MyDrive/best_swin.pth',

    # ── DICOM preprocessing ────────────────────────────────────
    'IMG_SIZE':     224,       # Swin-Tiny expects 224x224
    'WINDOW_CENTER': 40,       # Soft tissue window (good for pelvis/ovaries)
    'WINDOW_WIDTH':  400,      # Soft tissue window width
    'PELVIC_Z_MIN': -200,      # mm below body center (pelvic region start)
    'PELVIC_Z_MAX':  50,       # mm above body center (pelvic region end)

    # ── Sampling ───────────────────────────────────────────────
    'MAX_SLICES_PER_PATIENT': 20,  # sample up to 20 slices per patient
    'MIN_SLICES_PER_PATIENT':  5,  # skip patients with fewer slices

    # ── Training ───────────────────────────────────────────────
    'BATCH_SIZE':   16,
    'NUM_EPOCHS':   30,
    'LR':           1e-4,
    'PATIENCE':     8,
    'VAL_SPLIT':    0.15,
    'TEST_SPLIT':   0.15,
    'SEED':         42,
    'NUM_WORKERS':  2,
}

random.seed(CONFIG['SEED'])
np.random.seed(CONFIG['SEED'])
torch.manual_seed(CONFIG['SEED'])
print('Config ready.')

class DICOMDataset(Dataset):
    """
    PyTorch Dataset that reads .dcm files directly.
    No PNG/JPEG conversion. Works with raw DICOM.

    Each __getitem__ call:
      1. Reads the .dcm file with pydicom
      2. Converts to HU
      3. Applies soft-tissue windowing
      4. Resizes to 224x224
      5. Returns (tensor, label)
    """
    def __init__(self, paths, labels, config, augment=False):
        self.paths   = paths
        self.labels  = labels
        self.config  = config
        self.augment = augment

    def __len__(self):
        return len(self.paths)

    def __getitem__(self, idx):
        path  = self.paths[idx]
        label = self.labels[idx]

        # Read and preprocess the DICOM file
        tensor = read_dicom_slice(
            path,
            window_center=self.config['WINDOW_CENTER'],
            window_width =self.config['WINDOW_WIDTH'],
            img_size     =self.config['IMG_SIZE']
        )

        if tensor is None:
            # Return a blank tensor if DICOM read fails
            tensor = torch.zeros(3, self.config['IMG_SIZE'], self.config['IMG_SIZE'])

        # ── Optional augmentation (train only) ───────────────────
        if self.augment:
            tensor = self._augment(tensor)

        return tensor, torch.tensor(label, dtype=torch.long)

    def _augment(self, tensor):
        """Simple augmentations that work on tensors."""
        # Random horizontal flip
        if random.random() > 0.5:
            tensor = torch.flip(tensor, dims=[2])
        # Random vertical flip
        if random.random() > 0.5:
            tensor = torch.flip(tensor, dims=[1])
        # Random brightness jitter
        if random.random() > 0.5:
            factor = random.uniform(0.9, 1.1)
            tensor = tensor * factor
        return tensor


# ── Create DataLoaders ────────────────────────────────────────────────────
train_ds = DICOMDataset(X_tr,  y_tr,  CONFIG, augment=True)
val_ds   = DICOMDataset(X_val, y_val, CONFIG, augment=False)
test_ds  = DICOMDataset(X_te,  y_te,  CONFIG, augment=False)

train_loader = DataLoader(train_ds, batch_size=CONFIG['BATCH_SIZE'],
                          shuffle=True,  num_workers=CONFIG['NUM_WORKERS'],
                          pin_memory=True)
val_loader   = DataLoader(val_ds,   batch_size=CONFIG['BATCH_SIZE'],
                          shuffle=False, num_workers=CONFIG['NUM_WORKERS'],
                          pin_memory=True)
test_loader  = DataLoader(test_ds,  batch_size=CONFIG['BATCH_SIZE'],
                          shuffle=False, num_workers=CONFIG['NUM_WORKERS'],
                          pin_memory=True)

print(f'DataLoaders ready:')
print(f'  Train batches : {len(train_loader)}')
print(f'  Val   batches : {len(val_loader)}')
print(f'  Test  batches : {len(test_loader)}')

fig, axes = plt.subplots(2, 4, figsize=(16, 8))
class_names = ['Healthy', 'Diseased']
class_colors = ['#4CAF50', '#F44336']

# Show 4 diseased + 4 healthy samples
for row, label in enumerate([0, 1]):
    class_paths = [p for p, l in zip(X_tr, y_tr) if l == label][:4]
    for col, path in enumerate(class_paths):
        ds = pydicom.dcmread(path)
        hu = ds.pixel_array.astype(np.float32) * \
             float(getattr(ds, 'RescaleSlope', 1.0)) + \
             float(getattr(ds, 'RescaleIntercept', 0.0))
        img = apply_window(hu, CONFIG['WINDOW_CENTER'], CONFIG['WINDOW_WIDTH'])

        axes[row, col].imshow(img, cmap='gray')
        axes[row, col].set_title(
            f'{class_names[label]}',
            color=class_colors[label], fontweight='bold'
        )
        axes[row, col].axis('off')

plt.suptitle('Sample CT Slices — Soft Tissue Window (WC=40, WW=400)',
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()
print('Slices look correct if you can see soft tissue detail.')

class SwinCTClassifier(nn.Module):
    """
    Swin-Tiny pretrained on ImageNet, fine-tuned for
    binary CT classification (healthy vs ovarian cancer).

    Input:  (B, 3, 224, 224)  — 3-channel grayscale CT slice
    Output: (B, 2)            — logits for [healthy, diseased]
    """
    def __init__(self, num_classes=2, dropout=0.3):
        super().__init__()
        # Load pretrained Swin-Tiny (same as your swin_model.ipynb)
        self.backbone = timm.create_model(
            'swin_tiny_patch4_window7_224',
            pretrained=True,
            num_classes=0   # remove head → returns 768-d features
        )
        feat_dim = self.backbone.num_features  # 768 for Swin-Tiny

        # Custom classification head
        self.head = nn.Sequential(
            nn.LayerNorm(feat_dim),
            nn.Dropout(dropout),
            nn.Linear(feat_dim, 256),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(256, num_classes)
        )

    def forward(self, x):
        features = self.backbone(x)   # (B, 768)
        return self.head(features)    # (B, 2)


model = SwinCTClassifier(num_classes=2, dropout=0.3).to(device)

n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f'Model ready — Trainable params: {n_params:,}')

# ── Class-weighted loss (handles imbalance) ───────────────────────────────
class_counts = [y_tr.count(0), y_tr.count(1)]
total = sum(class_counts)
weights = torch.tensor(
    [total / (2 * c) for c in class_counts],
    dtype=torch.float32
).to(device)
criterion = nn.CrossEntropyLoss(weight=weights)
print(f'Class weights: healthy={weights[0]:.3f}, diseased={weights[1]:.3f}')

# ── Optimizer: lower LR for backbone, higher for head ────────────────────
optimizer = optim.AdamW([
    {'params': model.backbone.parameters(), 'lr': CONFIG['LR'] * 0.1},
    {'params': model.head.parameters(),     'lr': CONFIG['LR']},
], weight_decay=1e-4)

scheduler = optim.lr_scheduler.CosineAnnealingLR(
    optimizer, T_max=CONFIG['NUM_EPOCHS']
)
print('Optimizer ready.')

def train_one_epoch(model, loader, optimizer, criterion, device):
    model.train()
    total_loss, preds_all, labels_all = 0.0, [], []

    for images, labels in tqdm(loader, desc='Training', leave=False):
        images, labels = images.to(device), labels.to(device)
        optimizer.zero_grad()
        logits = model(images)
        loss   = criterion(logits, labels)
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()

        total_loss += loss.item()
        preds_all.extend(logits.argmax(1).cpu().numpy())
        labels_all.extend(labels.cpu().numpy())

    return total_loss / len(loader), accuracy_score(labels_all, preds_all)


@torch.no_grad()
def evaluate(model, loader, criterion, device):
    model.eval()
    total_loss, preds_all, labels_all, probs_all = 0.0, [], [], []

    for images, labels in tqdm(loader, desc='Evaluating', leave=False):
        images, labels = images.to(device), labels.to(device)
        logits = model(images)
        total_loss += criterion(logits, labels).item()
        probs = F.softmax(logits, dim=1)[:, 1].cpu().numpy()
        preds_all.extend(logits.argmax(1).cpu().numpy())
        labels_all.extend(labels.cpu().numpy())
        probs_all.extend(probs)

    return (
        total_loss / len(loader),
        np.array(labels_all),
        np.array(preds_all),
        np.array(probs_all)
    )


print('Training functions ready.')

best_val_loss  = float('inf')
patience_count = 0
history = {'train_loss': [], 'val_loss': [], 'train_acc': [], 'val_acc': []}

print('─── Training (DICOM → Swin Transformer) ───────────────────────────────')
print(f'{"Epoch":>6} {"Tr Loss":>9} {"Tr Acc":>8} {"Vl Loss":>9} {"Vl Acc":>8}')
print('─' * 55)

for epoch in range(1, CONFIG['NUM_EPOCHS'] + 1):
    tr_loss, tr_acc = train_one_epoch(model, train_loader, optimizer, criterion, device)
    vl_loss, y_vt, y_vp, _ = evaluate(model, val_loader, criterion, device)
    vl_acc = accuracy_score(y_vt, y_vp)
    scheduler.step()

    history['train_loss'].append(tr_loss)
    history['val_loss'].append(vl_loss)
    history['train_acc'].append(tr_acc)
    history['val_acc'].append(vl_acc)

    print(f'{epoch:6d} {tr_loss:9.4f} {tr_acc:8.4f} {vl_loss:9.4f} {vl_acc:8.4f}')

    if vl_loss < best_val_loss:
        best_val_loss = vl_loss
        patience_count = 0
        torch.save({
            'model_state': model.state_dict(),
            'config': CONFIG,
            'epoch': epoch,
        }, CONFIG['CKPT_PATH'])
        print(f'  ✓ Checkpoint saved (val_loss={vl_loss:.4f})')
    else:
        patience_count += 1
        if patience_count >= CONFIG['PATIENCE']:
            print(f'\nEarly stopping at epoch {epoch}.')
            break

print('\nTraining complete.')

# Load best checkpoint
ckpt = torch.load(CONFIG['CKPT_PATH'], map_location=device, weights_only=False)
model.load_state_dict(ckpt['model_state'])
print(f"Loaded best model from epoch {ckpt['epoch']}")

_, y_true, y_pred, y_prob = evaluate(model, test_loader, criterion, device)

print('\n─── Test Results ─────────────────────────────────────────────────────')
print(f'  Accuracy  : {accuracy_score(y_true, y_pred):.4f}')
print(f'  F1-Score  : {f1_score(y_true, y_pred, zero_division=0):.4f}')
if len(np.unique(y_true)) > 1:
    print(f'  ROC-AUC   : {roc_auc_score(y_true, y_prob):.4f}')

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Loss
axes[0].plot(history['train_loss'], label='Train', color='#2196F3')
axes[0].plot(history['val_loss'],   label='Val',   color='#F44336')
axes[0].set_title('Loss'); axes[0].set_xlabel('Epoch')
axes[0].legend(); axes[0].grid(alpha=0.3)

# Accuracy
axes[1].plot(history['train_acc'], label='Train', color='#2196F3')
axes[1].plot(history['val_acc'],   label='Val',   color='#F44336')
axes[1].set_title('Accuracy'); axes[1].set_xlabel('Epoch')
axes[1].legend(); axes[1].grid(alpha=0.3)

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[2],
            xticklabels=['Healthy', 'Diseased'],
            yticklabels=['Healthy', 'Diseased'])
axes[2].set_title('Confusion Matrix')
axes[2].set_ylabel('Actual'); axes[2].set_xlabel('Predicted')

plt.suptitle('Swin Transformer — DICOM CT Classification', fontsize=14, fontweight='bold')
plt.tight_layout(); plt.show()

# ROC Curve
if len(np.unique(y_true)) > 1:
    fpr, tpr, _ = roc_curve(y_true, y_prob)
    auc = roc_auc_score(y_true, y_prob)
    plt.figure(figsize=(6, 5))
    plt.plot(fpr, tpr, color='#2196F3', lw=2, label=f'AUC = {auc:.3f}')
    plt.plot([0, 1], [0, 1], 'k--')
    plt.xlabel('False Positive Rate'); plt.ylabel('True Positive Rate')
    plt.title('ROC Curve — DICOM CT (Healthy vs Ovarian Cancer)')
    plt.legend(); plt.grid(alpha=0.3); plt.tight_layout(); plt.show()