# -*- coding: utf-8 -*-
"""swin_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-sYVcv4t93J26J6AGwS3CFndw5D30nxj
"""

!pip install pydicom timm torch torchvision numpy scikit-learn matplotlib seaborn tqdm
!pip install monai  # optional but great for medical DICOM handling

import os
import glob
import random
import numpy as np
import pydicom
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import timm
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import (
    accuracy_score, f1_score, roc_auc_score,
    confusion_matrix, roc_curve
)
from sklearn.model_selection import train_test_split
from tqdm import tqdm

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device: {device}')
if torch.cuda.is_available():
    print(f'GPU: {torch.cuda.get_device_name(0)}')

from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

import zipfile
import os

healthy_zip = "/content/drive/MyDrive/data/health.zip"
disease_zip = "/content/drive/MyDrive/data/disease.zip"

healthy_extract = "/content/Mydrive/healthy"
disease_extract = "/content/Mydrive/diseased"

# Extract healthy
if not os.path.exists(healthy_extract):
    with zipfile.ZipFile(healthy_zip, 'r') as zip_ref:
        zip_ref.extractall(healthy_extract)

# Extract disease
if not os.path.exists(disease_extract):
    with zipfile.ZipFile(disease_zip, 'r') as zip_ref:
        zip_ref.extractall(disease_extract)

print("✅ Both datasets extracted")

import glob
import pydicom

def find_axial_series(patient_dir):
    all_dcm = glob.glob(
        os.path.join(patient_dir, '**', '*.dcm'),
        recursive=True
    )

    series_dict = {}

    for dcm_path in all_dcm:
        try:
            ds = pydicom.dcmread(dcm_path, stop_before_pixels=True)

            series_uid = str(getattr(ds, 'SeriesInstanceUID', 'unknown'))

            image_type = list(getattr(ds, 'ImageType', []))
            if 'LOCALIZER' in image_type or 'SCOUT' in image_type:
                continue

            desc = str(getattr(ds, 'SeriesDescription', '')).upper()

            # Skip non-axial
            if any(x in desc for x in ['CORONAL', 'SAGITTAL', 'MPR', 'REFORMAT']):
                continue

            if series_uid not in series_dict:
                series_dict[series_uid] = []

            series_dict[series_uid].append(dcm_path)

        except:
            continue

    if not series_dict:
        return all_dcm

    best_series = max(series_dict.values(), key=len)
    return sorted(best_series)

import numpy as np

def get_hu_image(dcm):
    img = dcm.pixel_array.astype(np.float32)

    slope = getattr(dcm, "RescaleSlope", 1)
    intercept = getattr(dcm, "RescaleIntercept", 0)

    return img * slope + intercept


def is_pelvic_slice(dcm):
    hu = get_hu_image(dcm)

    # Tissue + bone region
    mask = (hu > -200) & (hu < 300)

    ratio = np.sum(mask) / mask.size

    return ratio > 0.15

MAX_SLICES = 64

def sample_slices(dcm_files):
    if len(dcm_files) <= MAX_SLICES:
        return dcm_files

    step = len(dcm_files) // MAX_SLICES
    return dcm_files[::step][:MAX_SLICES]

import shutil
from tqdm import tqdm

healthy_root = os.path.join(healthy_extract, "health")
healthy_output = "/content/Mydrive/healthy/health"

os.makedirs(healthy_output, exist_ok=True)

count_h = 0

for patient in tqdm(os.listdir(healthy_root)):
    patient_path = os.path.join(healthy_root, patient)

    if not os.path.isdir(patient_path):
        continue

    try:
        # 🔥 NEW: automatically get best axial series
        axial_files = find_axial_series(patient_path)

        if len(axial_files) < 10: continue
        if len(pelvic_files) < 5: continue

        pelvic_files = []

        for dcm_path in axial_files:
            try:
                dcm = pydicom.dcmread(dcm_path)

                if is_pelvic_slice(dcm):
                    pelvic_files.append(dcm_path)

            except:
                continue

        if len(pelvic_files) < 20:
            continue

        save_path = os.path.join(healthy_output, patient)
        os.makedirs(save_path, exist_ok=True)

        for f in pelvic_files:
            shutil.copy2(f, os.path.join(save_path, os.path.basename(f)))

        count_h += 1

    except:
        continue

print("✅ Healthy processed:", count_h)

print("Axial:", len(axial_files), "Pelvic:", len(pelvic_files))

!ls /content/Mydrive/healthy/health

print("Healthy patients:", len(os.listdir(healthy_root)))

disease_root = os.path.join(disease_extract, "disease")
disease_output = "/content/MyDrive/dataset/diseased"

os.makedirs(disease_output, exist_ok=True)

count_d = 0

for patient in tqdm(os.listdir(disease_root)):
    patient_path = os.path.join(disease_root, patient)

    if not os.path.isdir(patient_path):
        continue

    all_dcm = glob.glob(
        os.path.join(patient_path, '**', '*.dcm'),
        recursive=True
    )

    if len(all_dcm) < 20:
        continue

    save_path = os.path.join(disease_output, patient)
    os.makedirs(save_path, exist_ok=True)

    for f in all_dcm:
        shutil.copy2(f, os.path.join(save_path, os.path.basename(f)))

    count_d += 1

print("✅ Diseased processed:", count_d)

def count_dicoms(path):
    total = 0
    for root, _, files in os.walk(path):
        total += len([f for f in files if f.endswith(".dcm")])
    return total

print("Healthy slices:", count_dicoms("/content/MyDrive/dataset/healthy"))
print("Diseased slices:", count_dicoms("/content/MyDrive/dataset/diseased"))

import random
import os

def get_all_files(path):
    files = []
    for root, _, f in os.walk(path):
        for file in f:
            if file.endswith(".dcm"):
                files.append(os.path.join(root, file))
    return files

healthy_files = get_all_files("/content/MyDrive/dataset/healthy")
diseased_files = get_all_files("/content/MyDrive/dataset/diseased")

min_count = min(len(healthy_files), len(diseased_files))

healthy_files = random.sample(healthy_files, min_count)
diseased_files = random.sample(diseased_files, min_count)

print("Balanced count:", min_count)

import random
import matplotlib.pyplot as plt
import pydicom

def show_random_samples(healthy_files, diseased_files, n=8):
    samples = random.sample(healthy_files, n//2) + random.sample(diseased_files, n//2)
    labels = ["healthy"]*(n//2) + ["diseased"]*(n//2)

    plt.figure(figsize=(12, 6))

    for i, (f, label) in enumerate(zip(samples, labels)):
        dcm = pydicom.dcmread(f)
        img = dcm.pixel_array

        plt.subplot(2, n//2, i+1)
        plt.imshow(img, cmap='gray')
        plt.title(label)
        plt.axis('off')

    plt.suptitle("Random Samples (Healthy vs Diseased)", fontsize=14)
    plt.show()

# CALL
show_random_samples(healthy_files, diseased_files, n=8)

def show_slice_progression(file_list, title="Slice Progression"):
    files = sorted(file_list)
    step = len(files)//6

    plt.figure(figsize=(12, 4))

    for i in range(6):
        dcm = pydicom.dcmread(files[i*step])
        img = dcm.pixel_array

        plt.subplot(1, 6, i+1)
        plt.imshow(img, cmap='gray')
        plt.title(f"Slice {i}")
        plt.axis('off')

    plt.suptitle(title)
    plt.show()

# CALL (example)
show_slice_progression(healthy_files)

def plot_histogram(file_path, title):
    dcm = pydicom.dcmread(file_path)
    img = dcm.pixel_array.flatten()

    plt.hist(img, bins=50)
    plt.title(title)
    plt.xlabel("Pixel Intensity")
    plt.ylabel("Frequency")

# CALL
plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plot_histogram(healthy_files[0], "Healthy Histogram")

plt.subplot(1,2,2)
plot_histogram(diseased_files[0], "Diseased Histogram")

plt.show()

import cv2

def show_edges(dcm_path):
    dcm = pydicom.dcmread(dcm_path)
    img = dcm.pixel_array.astype(np.uint8)

    sobel = cv2.Sobel(img, cv2.CV_64F, 1, 1, ksize=5)
    canny = cv2.Canny(img, 100, 200)

    plt.figure(figsize=(10,4))

    plt.subplot(1,3,1)
    plt.imshow(img, cmap='gray')
    plt.title("Original")

    plt.subplot(1,3,2)
    plt.imshow(sobel, cmap='gray')
    plt.title("Sobel")

    plt.subplot(1,3,3)
    plt.imshow(canny, cmap='gray')
    plt.title("Canny")

    for i in range(3):
        plt.subplot(1,3,i+1).axis('off')

    plt.show()

# CALL
show_edges(diseased_files[0])

import cv2
import numpy as np
import pydicom
import matplotlib.pyplot as plt

dcm_path = "/content/MyDrive/dataset/diseased/2/1-149.dcm"

def highlight_tumor_clean(dcm_path):
    # Load DICOM
    dcm = pydicom.dcmread(dcm_path)
    img = dcm.pixel_array.astype(np.float32)

    # Normalize
    img = (img - np.min(img)) / (np.max(img) - np.min(img))
    img = (img * 255).astype(np.uint8)

    h, w = img.shape

    # Focus center region (pelvic area)
    center_crop = img[int(h*0.2):int(h*0.8), int(w*0.2):int(w*0.8)]

    # Blur
    blurred = cv2.GaussianBlur(center_crop, (5,5), 0)

    # Adaptive threshold (better than fixed)
    thresh = cv2.adaptiveThreshold(
        blurred, 255,
        cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
        cv2.THRESH_BINARY,
        11, 2
    )

    # Find contours
    contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    # Convert to color
    img_color = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)

    best_cnt = None
    max_area = 0

    for cnt in contours:
        area = cv2.contourArea(cnt)

        if 300 < area < 5000:  # filter noise + huge areas
            if area > max_area:
                max_area = area
                best_cnt = cnt

    # Draw best contour
    if best_cnt is not None:
        (x, y), radius = cv2.minEnclosingCircle(best_cnt)

        # Adjust back to original coordinates
        x += int(w*0.2)
        y += int(h*0.2)

        center = (int(x), int(y))
        radius = int(radius)

        cv2.circle(img_color, center, radius, (255, 0, 0), 3)
        cv2.putText(img_color, "Tumor Region",
                    (center[0]-40, center[1]-radius-10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255,0,0), 1)

    # Plot
    plt.figure(figsize=(10,4))

    plt.subplot(1,2,1)
    plt.imshow(img, cmap='gray')
    plt.title("Original")

    plt.subplot(1,2,2)
    plt.imshow(img_color)
    plt.title("Tumor Highlighted")

    plt.axis('off')
    plt.show()

highlight_tumor_clean(dcm_path)